package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    private JoinPredicate joinPredicate;
    private final DbIterator[] children = new DbIterator[2];
    private Tuple tuple;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        // some code goes here
    	this.joinPredicate = p;
    	this.children[0] = child1;
    	this.children[1] = child2;
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return this.joinPredicate;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return this.children[0].getTupleDesc().getFieldName(joinPredicate.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return this.children[1].getTupleDesc().getFieldName(joinPredicate.getField2());
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(this.children[0].getTupleDesc(), this.children[1].getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
    	super.open();
    	this.children[0].open();
    	this.children[1].open();
    }

    public void close() {
        // some code goes here
    	super.close();
    	this.children[0].close();
    	this.children[1].close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
    	this.children[0].rewind();
    	this.children[1].rewind();
    	this.tuple = null;
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
    	if (tuple == null && children[0].hasNext()) {
    		tuple = children[0].next();
    	}
    	while (tuple != null) {
    		while (children[1].hasNext()) {
    			Tuple tupleChild2 = children[1].next();
    			if (joinPredicate.filter(tuple, tupleChild2)) {
    				Tuple merged = new Tuple(this.getTupleDesc());
    				int numField1 = tuple.getTupleDesc().numFields();
    				int numField2 = tupleChild2.getTupleDesc().numFields();
    				for (int i=0; i < numField1; i++) {
    					merged.setField(i, tuple.getField(i));
    				}
    				for (int j=0; j < numField2; j++) {
    					merged.setField(j + numField1, tupleChild2.getField(j));
    				}
    				return merged;
    			}
    		}
    		if (children[0].hasNext()) {
    			tuple = children[0].next();
    		} else {
    			tuple = null;
    		}
    		children[1].rewind();
    	}
        return null;
    }

    @Override
    public DbIterator[] getChildren() {
        // some code goes here
        return new DbIterator[] {this.children[0], this.children[1]};
    }

    @Override
    public void setChildren(DbIterator[] children) {
        // some code goes here
    	this.children[0] = children[0];
    	this.children[1] = children[1];
    }

}
